//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultationProject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor_info()
        {
            this.appointments = new HashSet<appointment>();
            this.doctor_schedule = new HashSet<doctor_schedule>();
        }
    
        public int d_id { get; set; }
        public Nullable<int> d_govid { get; set; }
        public string d_degree { get; set; }
        public string d_specialty { get; set; }
        public Nullable<int> u_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
        public virtual doctor_info doctor_info1 { get; set; }
        public virtual doctor_info doctor_info2 { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doctor_schedule> doctor_schedule { get; set; }
    }
}
